<?php

class OperacionReal extends Operacion
{

    public function __construct(string $cadena)
    {
        parent::__construct($cadena);
    }

    public function operar($op1, $op2, $operador)
    {
        switch ($this->operador){
            case '+':
                return $this->op1 + $this->op2;
                break;
        }
    }



    public function __toString(): string
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}